/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 *
 * @author louza
 */
public class TelaEspada extends javax.swing.JPanel {

    /**
     * Creates new form TelaJogo
     */
    public TelaEspada() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        EspadaOp2 = new javax.swing.JButton();
        EspadaOp4 = new javax.swing.JButton();
        EspadaOp3 = new javax.swing.JButton();
        Escolha.setEditable(false);
        Escolha = new javax.swing.JTextField();
        EspadaOp1 = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();

        jButton1.setText("jButton1");

        jLabel2.setBackground(new java.awt.Color(204, 204, 255));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 102, 0));
        jLabel2.setText("JOGO DE TURNOS");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 102, 0));
        jLabel4.setText("ESPADA");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 102, 0));
        jLabel5.setText("ESCOLHA O GOLPE:");

        EspadaOp2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        EspadaOp2.setText("CORTE PROFUNDO");
        EspadaOp2.setAlignmentX(0.5F);
        EspadaOp2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                EspadaOp2MousePressed(evt);
            }
        });
        EspadaOp2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EspadaOp2ActionPerformed(evt);
            }
        });

        EspadaOp4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        EspadaOp4.setText("ESPIRITO DA ESPADA");
        EspadaOp4.setAlignmentX(0.5F);
        EspadaOp4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                EspadaOp4MousePressed(evt);
            }
        });

        EspadaOp3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        EspadaOp3.setText("CORTE BAIXO");
        EspadaOp3.setAlignmentX(0.5F);
        EspadaOp3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                EspadaOp3MousePressed(evt);
            }
        });
        EspadaOp3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EspadaOp3ActionPerformed(evt);
            }
        });

        Escolha.setForeground(new java.awt.Color(51, 102, 0));
        Escolha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EscolhaActionPerformed(evt);
            }
        });

        EspadaOp1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        EspadaOp1.setText("CORTE SIMPLES");
        EspadaOp1.setAlignmentX(0.5F);
        EspadaOp1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                EspadaOp1MousePressed(evt);
            }
        });
        EspadaOp1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EspadaOp1ActionPerformed(evt);
            }
        });

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 102, 0));
        jLabel6.setText("VIDA ATUAL:   ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel5)
                            .addComponent(Escolha)
                            .addComponent(EspadaOp1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(EspadaOp2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(EspadaOp4, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                            .addComponent(EspadaOp3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(160, 160, 160)
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel2))))
                .addContainerGap(65, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Escolha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(EspadaOp1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(EspadaOp2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(EspadaOp3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(EspadaOp4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 5, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void EspadaOp2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EspadaOp2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EspadaOp2ActionPerformed

    private void EspadaOp1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EspadaOp1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EspadaOp1ActionPerformed

    private void EspadaOp3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EspadaOp3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EspadaOp3ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void EspadaOp1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EspadaOp1MousePressed
        // TODO add your handling code here:
        Escolha.setText("Corte Simples");
    }//GEN-LAST:event_EspadaOp1MousePressed

    private void EspadaOp2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EspadaOp2MousePressed
        // TODO add your handling code here:
        Escolha.setText("Corte Profundo");
    }//GEN-LAST:event_EspadaOp2MousePressed

    private void EspadaOp3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EspadaOp3MousePressed
        // TODO add your handling code here:
        Escolha.setText("Corte Baixo");
    }//GEN-LAST:event_EspadaOp3MousePressed

    private void EspadaOp4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EspadaOp4MousePressed
        // TODO add your handling code here:
        Escolha.setText("Espírito de Espada");
    }//GEN-LAST:event_EspadaOp4MousePressed

    private void EscolhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EscolhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EscolhaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Escolha;
    private javax.swing.JButton EspadaOp1;
    private javax.swing.JButton EspadaOp2;
    private javax.swing.JButton EspadaOp3;
    private javax.swing.JButton EspadaOp4;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
