/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author louza
 */
public class TelaCajado extends javax.swing.JFrame {

    /**
     * Creates new form TelaCajado
     */
    public TelaCajado() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        CAJADOOP2 = new javax.swing.JButton();
        CAJADOOP4 = new javax.swing.JButton();
        CAJADOOP3 = new javax.swing.JButton();
        Escolha.setEditable(false);
        Escolha = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        CAJADOOP1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 102, 0));
        jLabel6.setText("VIDA ATUAL:   ");
        jLabel6.setAlignmentX(1.0F);
        jLabel6.setAlignmentY(1.0F);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 102, 0));
        jLabel5.setText("ESCOLHA O GOLPE:");
        jLabel5.setAlignmentX(1.0F);
        jLabel5.setAlignmentY(1.0F);

        CAJADOOP2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        CAJADOOP2.setText("CAJADADA");
        CAJADOOP2.setAlignmentX(1.0F);
        CAJADOOP2.setAlignmentY(1.0F);
        CAJADOOP2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                CAJADOOP2MousePressed(evt);
            }
        });
        CAJADOOP2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CAJADOOP2ActionPerformed(evt);
            }
        });

        CAJADOOP4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        CAJADOOP4.setText("CURA DAS CHAMAS");
        CAJADOOP4.setAlignmentX(1.0F);
        CAJADOOP4.setAlignmentY(1.0F);
        CAJADOOP4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                CAJADOOP4MousePressed(evt);
            }
        });

        CAJADOOP3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        CAJADOOP3.setText("REDEMOINHO DE FOGO");
        CAJADOOP3.setAlignmentX(1.0F);
        CAJADOOP3.setAlignmentY(1.0F);
        CAJADOOP3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                CAJADOOP3MousePressed(evt);
            }
        });

        Escolha.setForeground(new java.awt.Color(51, 102, 0));
        Escolha.setAlignmentX(1.0F);
        Escolha.setAlignmentY(1.0F);

        jLabel2.setBackground(new java.awt.Color(204, 204, 255));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 102, 0));
        jLabel2.setText("JOGO DE TURNOS");
        jLabel2.setAlignmentX(1.0F);
        jLabel2.setAlignmentY(1.0F);

        CAJADOOP1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        CAJADOOP1.setText("BOLA DE FOGO");
        CAJADOOP1.setAlignmentX(1.0F);
        CAJADOOP1.setAlignmentY(1.0F);
        CAJADOOP1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                CAJADOOP1MousePressed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 102, 0));
        jLabel4.setText("CAJADO");
        jLabel4.setAlignmentX(1.0F);
        jLabel4.setAlignmentY(1.0F);

        jTextField2.setAlignmentX(1.0F);
        jTextField2.setAlignmentY(1.0F);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(160, 160, 160)
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(CAJADOOP3, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Escolha, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CAJADOOP1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CAJADOOP4, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CAJADOOP2, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Escolha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CAJADOOP1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(CAJADOOP2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CAJADOOP3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CAJADOOP4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(3, 3, 3))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CAJADOOP2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CAJADOOP2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CAJADOOP2ActionPerformed

    private void CAJADOOP1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CAJADOOP1MousePressed
        // TODO add your handling code here:
        Escolha.setText("Bola de Fogo");
    }//GEN-LAST:event_CAJADOOP1MousePressed

    private void CAJADOOP2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CAJADOOP2MousePressed
        // TODO add your handling code here:
        Escolha.setText("Cajadada");
    }//GEN-LAST:event_CAJADOOP2MousePressed

    private void CAJADOOP3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CAJADOOP3MousePressed
        // TODO add your handling code here:
        Escolha.setText("Redemoinho de Fogo");
    }//GEN-LAST:event_CAJADOOP3MousePressed

    private void CAJADOOP4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CAJADOOP4MousePressed
        // TODO add your handling code here:
        Escolha.setText("Cura das Chamas");
    }//GEN-LAST:event_CAJADOOP4MousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCajado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCajado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCajado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCajado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCajado().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CAJADOOP1;
    private javax.swing.JButton CAJADOOP2;
    private javax.swing.JButton CAJADOOP3;
    private javax.swing.JButton CAJADOOP4;
    private javax.swing.JTextField Escolha;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
